<?php

use Illuminate\Database\Seeder;
use App\Thread;

class ThreadsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      Thread::truncate();

      $list = [
        "AI",
"相川七瀬",
"あいくれ",
"aiko",
"會田茂一",
"i-dep",
"IDOL PUNCH",
"I Don't Like Mondays.",
"相葉雅紀",
"アイビーカラー",
"I Promised Once",
"IVORY7 CHORD",
"あいまいより。",
"あいみょん",
"I'M FLASH! BAND",
"I-RabBits",
"Aira Mitsuki",
"the irony",
"Ain Figremin",
"Ivy to Fraudulent Game",
"蒼井優",
"out at bero",
"outside yoshino",
"OUTRAGE",
"藍井エイル",
"蒼井翔太",
"青葉市子",
"藍坊主",
"青山テルマ",
"赤い疑惑",
"赤い公園",
"赤犬",
"赤い猫",
"赤色のグリッター",
"AKAKAGE",
"アカシアオルケスタ",
"アカシック",
"acari",
"aquarifa",
"あがた森魚",
"上妻宏光",
"秋休",
"秋山黄色",
"Aqua Timez",
"THE ACT WE ACT",
"AKLO",
"ACROBAT ATHLETE",
"agraph",
"明星/Akeboshi",
"ACO",
"浅井健一",
"1000say",
"浅草ジンタ",
"ASA-CHANG",
"ASA-CHANG&amp;巡礼",
"浅野忠信",
"ASAYAKE01",
"アシガルユース",
"Acita",
"Acid Black Cherry",
"ACIDMAN",
"Ashleigh Mannix",
"ASIAN KUNG-FU GENERATION",
"AJICO",
"AJISAI",
"ASKA",
"ASCA",
"アスタラビスタ",
"ASPARAGUS",
"asphalt frustration",
"asobius",
"ATATA",
"Attack Come Backer",
"atami",
"新しい学校のリーダーズ",
"中孝介",
"あだち麗三郎",
"ADAM at",
"ASH DA HERO",
"at Anytime",
"あっぱ",
"UPPER",
"アップアップガールズ(仮)",
"UPLIFT SPICE",
"アップル斎藤と愉快なヘラクレスたち",
"厚見玲衣（ex.VOWWOW）",
"Atomic stooges",
"ATOM ON SPHERE",
"Attractions",
"ATLANTIS AIRPORT",
"another sunnyday",
"Another Story",
"ANATAKIKOU",
"アナム&amp;マキ",
"Analogfish",
"アナーキー",
"ANARCHY STONE",
"ANIMETAL",
"アニメーションズ",
"Anny",
"annie the clumsy",
"ano-Hi",
"about tess",
"about me",
"abingdon boys school",
"After the Rain",
"AFRA",
"Afra &amp; Incredible Beatbox Band",
"a flood of circle",
"あふりらんぽ",
"A.F.R.O",
"ABSTRACT MASH",
"ABSOLUTION",
"Absolute area",
"Applicat Spectra",
"阿部サダヲ",
"ABEDON",
"阿部芙蓉美",
"阿部真央",
"avengers in sci-fi",
"APOGEE",
"Apollo（eleven）",
"amazarashi",
"天月-あまつき-",
"安室奈美恵",
"雨上がり決死隊",
"雨先案内人",
"雨のパレード",
      ];

      $faker = Faker\Factory::create('ja_JP');
      foreach ($list as $key => $li) {
        DB::table('threads')->insert([
          'user_id' => $key,
          // 'title' => $faker->realText($maxNbChars = rand(10,25), $indexSize = 2),
          'title' => $list[$key],
          "created_at" => date("Y/m/d H:i:s"),
          "updated_at" => date("Y/m/d H:i:s"),
        ]);
      }

    }
}
